<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\FoodCategory;
use Illuminate\Database\Seeder;

class FoodCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'key' => 'sushi',
                'name' => 'Sushi & Sashimi',
                'aliases' => ['salmon sushi', 'tuna sushi', 'sashimi', 'maki', 'nigiri', 'omakase', 'temaki'],
                'visual_keywords' => [
                    'glistening raw fish slices', 'perfect rice mold', 'vibrant salmon orange',
                    'wasabi and ginger accent', 'dramatic dark plate contrast',
                ],
                'texture_descriptors' => ['silky smooth fish', 'tender flesh', 'translucent sheen', 'fresh and moist'],
                'lighting_preset' => 'soft diffused side lighting, slight backlight for translucency, dark moody background',
                'camera_angle' => '45 degree overhead or close macro shot',
                'plating_style' => 'dark slate or black ceramic plate, minimal garnish, soy sauce in small dish, single bamboo leaf accent',
                'color_palette' => ['deep salmon orange', 'pearl white rice', 'dark charcoal plate', 'bright wasabi green'],
                'avoid' => ['overcooked look', 'dry edges', 'messy plating', 'bright white background', 'chopsticks crossing'],
                'cuisine_affinity' => ['japanese'],
                'sort_order' => 1,
            ],
            [
                'key' => 'kopi',
                'name' => 'Kopi & Espresso',
                'aliases' => ['coffee', 'espresso', 'latte', 'cappuccino', 'cold brew', 'kopi susu', 'V60', 'pour over', 'flat white', 'americano', 'kopi hitam'],
                'visual_keywords' => [
                    'perfectly poured latte art rosette', 'steam wisps rising from cup',
                    'rich dark crema', 'condensation on cold brew glass', 'golden espresso extraction',
                ],
                'texture_descriptors' => ['silky microfoam', 'glossy dark liquid', 'creamy milk layer', 'velvety smooth'],
                'lighting_preset' => 'warm golden side lighting 45 degrees, soft shadows, cafe ambient feel, slight warmth',
                'camera_angle' => 'overhead flat lay OR 3/4 angle at eye level',
                'plating_style' => 'white or matte ceramic cup on saucer, wooden table surface, coffee beans artfully scattered, small biscotti optional',
                'color_palette' => ['deep espresso brown', 'cream ivory', 'warm amber', 'matte white'],
                'avoid' => ['paper cup', 'blurry foam art', 'overexposed white background', 'generic stock photo look', 'plastic straw'],
                'cuisine_affinity' => ['western_cafe', 'japanese_cafe', 'specialty_coffee'],
                'sort_order' => 2,
            ],
            [
                'key' => 'matcha',
                'name' => 'Matcha & Green Tea',
                'aliases' => ['green tea latte', 'matcha latte', 'hojicha', 'matchaccino', 'teh hijau', 'ocha'],
                'visual_keywords' => [
                    'vibrant ceremonial grade green', 'perfect foam layer',
                    'matcha powder dusted on top', 'serene japanese aesthetic',
                ],
                'texture_descriptors' => ['velvety smooth', 'earthy creamy', 'fine powder texture'],
                'lighting_preset' => 'soft natural daylight, clean and fresh, slight green tint enhancement',
                'camera_angle' => 'overhead flat lay or gentle 3/4 angle',
                'plating_style' => 'white ceramic cup or traditional chawan bowl, bamboo whisk as prop, clean minimalist surface',
                'color_palette' => ['vibrant matcha green', 'cream white', 'natural bamboo', 'soft sage'],
                'avoid' => ['dull brown-green color', 'uneven foam', 'cluttered background'],
                'cuisine_affinity' => ['japanese', 'japanese_cafe'],
                'sort_order' => 3,
            ],
            [
                'key' => 'steak',
                'name' => 'Steak & Wagyu',
                'aliases' => ['wagyu', 'ribeye', 'sirloin', 'tenderloin', 'daging panggang', 'beef steak', 'grilled beef'],
                'visual_keywords' => [
                    'perfect medium rare pink center', 'beautiful sear marks',
                    'glistening meat surface', 'herb butter melting on top', 'juicy beef texture',
                ],
                'texture_descriptors' => ['fine marbling throughout', 'crispy charred exterior', 'tender juicy interior'],
                'lighting_preset' => 'dramatic side lighting, warm tungsten, dark moody background, slight smoke effect',
                'camera_angle' => '45 degree side cut shot showing pink interior',
                'plating_style' => 'black cast iron skillet or dark wooden board, rosemary sprig, sea salt flakes, red wine jus drizzle',
                'color_palette' => ['deep charcoal sear', 'rosy pink interior', 'golden butter', 'dark background'],
                'avoid' => ['well done grey meat', 'pale unseared surface', 'bright white plate if moody style'],
                'cuisine_affinity' => ['western', 'fine_dining'],
                'sort_order' => 4,
            ],
            [
                'key' => 'ramen',
                'name' => 'Ramen & Mie',
                'aliases' => ['mie ramen', 'shoyu ramen', 'tonkotsu', 'miso ramen', 'ramyeon', 'noodle soup', 'mie ayam'],
                'visual_keywords' => [
                    'steaming broth with rising mist', 'perfectly arranged toppings',
                    'chashu pork slices', 'soft boiled egg halved', 'vibrant nori sheet',
                ],
                'texture_descriptors' => ['rich cloudy broth', 'springy noodles', 'tender pork belly'],
                'lighting_preset' => 'warm steam-lit, overhead with slight angle, dark cozy atmosphere',
                'camera_angle' => 'overhead 90 degrees OR slight angle showing depth',
                'plating_style' => 'deep ceramic bowl, toppings arranged clockwise, chopsticks resting on bowl edge',
                'color_palette' => ['rich amber broth', 'cream pork', 'dark nori', 'bright yellow egg'],
                'avoid' => ['dry noodles', 'cold-looking broth', 'messy random toppings'],
                'cuisine_affinity' => ['japanese'],
                'sort_order' => 5,
            ],
            [
                'key' => 'pasta',
                'name' => 'Pasta & Mie Italia',
                'aliases' => ['spaghetti', 'carbonara', 'aglio olio', 'fettuccine', 'penne', 'linguine', 'pasta bolognese'],
                'visual_keywords' => [
                    'perfectly twirled pasta nest', 'glossy sauce coating each strand',
                    'fresh parmesan shaved on top', 'herb garnish',
                ],
                'texture_descriptors' => ['silky sauce coating', 'al dente texture', 'creamy emulsified sauce'],
                'lighting_preset' => 'warm bistro lighting, soft and inviting',
                'camera_angle' => '45 degree angle showing height and twirl',
                'plating_style' => 'white wide-rim pasta bowl, twirled nest center, fresh basil leaf, crack of black pepper',
                'color_palette' => ['golden yellow pasta', 'rich red sauce', 'bright green herbs', 'white parmesan'],
                'avoid' => ['overcooked limp pasta', 'dry sauce', 'overfilled bowl'],
                'cuisine_affinity' => ['italian', 'western'],
                'sort_order' => 6,
            ],
            [
                'key' => 'burger',
                'name' => 'Burger & Sandwich',
                'aliases' => ['smash burger', 'beef burger', 'chicken burger', 'gourmet burger', 'cheeseburger', 'double patty'],
                'visual_keywords' => [
                    'perfect cross-section cut showing layers', 'melted cheese draping over patty',
                    'sesame seed brioche bun', 'fresh lettuce peek', 'juicy patty with char marks',
                ],
                'texture_descriptors' => ['crispy smashed patty edges', 'melty cheese pull', 'soft pillowy bun'],
                'lighting_preset' => 'bright natural or warm studio, slight backlight for cheese melt glow',
                'camera_angle' => 'straight side shot at eye level showing all layers',
                'plating_style' => 'parchment paper wrap, wooden board, side of crispy fries, small sauce ramekin',
                'color_palette' => ['golden brown bun', 'deep char patty', 'yellow melted cheese', 'vibrant green lettuce'],
                'avoid' => ['squashed flat burger', 'dry patty', 'bun hiding filling'],
                'cuisine_affinity' => ['western', 'western_cafe'],
                'sort_order' => 7,
            ],
            [
                'key' => 'dessert',
                'name' => 'Dessert & Kue',
                'aliases' => ['tiramisu', 'creme brulee', 'cheesecake', 'panna cotta', 'chocolate lava', 'molten cake', 'mousse', 'pudding', 'kue', 'cake'],
                'visual_keywords' => [
                    'perfect golden brulee crust', 'chocolate sauce flowing dramatically',
                    'berry coulis contrast', 'dusted cocoa powder', 'elegant plating with sauce dots',
                ],
                'texture_descriptors' => ['silky smooth', 'crisp sugar crust', 'molten flowing center', 'airy mousse'],
                'lighting_preset' => 'soft moody lighting, slight spotlight on hero, dark romantic background',
                'camera_angle' => '3/4 angle showing height and texture',
                'plating_style' => 'white fine dining plate, sauce swoosh, microgreens or edible flower accent, gold leaf optional',
                'color_palette' => ['rich chocolate brown', 'cream vanilla', 'deep berry red', 'gold accent'],
                'avoid' => ['collapsed structure', 'uneven dusting', 'flat boring plating'],
                'cuisine_affinity' => ['fine_dining', 'western', 'western_cafe'],
                'sort_order' => 8,
            ],
            [
                'key' => 'nasi',
                'name' => 'Nasi & Rice Dish',
                'aliases' => ['nasi goreng', 'nasi lemak', 'nasi bakar', 'rice bowl', 'nasi uduk', 'fried rice', 'nasi kuning'],
                'visual_keywords' => [
                    'perfectly mounded rice', 'golden fried rice with wok hei',
                    'colorful topping arrangement', 'crispy egg on top', 'traditional garnish of kerupuk',
                ],
                'texture_descriptors' => ['fluffy individual grains', 'slightly charred fried rice', 'glistening oil sheen'],
                'lighting_preset' => 'warm natural daylight, bright and appetizing',
                'camera_angle' => 'overhead flat lay or 45 degree showing toppings',
                'plating_style' => 'banana leaf lining or rustic ceramic plate, sambal in small bowl, cucumber slices, fried shallots scattered',
                'color_palette' => ['golden yellow rice', 'deep red sambal', 'bright green cucumber', 'crispy brown shallots'],
                'avoid' => ['clumped wet rice', 'pale unseasoned look', 'boring single color plate'],
                'cuisine_affinity' => ['indonesian'],
                'sort_order' => 9,
            ],
            [
                'key' => 'ayam',
                'name' => 'Ayam & Chicken',
                'aliases' => ['ayam goreng', 'fried chicken', 'ayam bakar', 'chicken wings', 'ayam geprek', 'crispy chicken', 'ayam penyet', 'grilled chicken'],
                'visual_keywords' => [
                    'perfectly crispy golden skin', 'juicy meat visible at cut',
                    'char marks on grilled pieces', 'steam rising from fresh cook',
                ],
                'texture_descriptors' => ['shatteringly crispy exterior', 'moist tender meat', 'caramelized marinade'],
                'lighting_preset' => 'warm bright natural light, appetizing and fresh',
                'camera_angle' => '45 degree showing crispy texture',
                'plating_style' => 'rustic wooden board or traditional plate, sambal lado, fresh tomato slices, lime wedge',
                'color_palette' => ['golden crispy brown', 'bright red sambal', 'fresh green garnish'],
                'avoid' => ['pale undercooked skin', 'greasy look', 'unappetizing dark burn'],
                'cuisine_affinity' => ['indonesian', 'western'],
                'sort_order' => 10,
            ],
            [
                'key' => 'seafood',
                'name' => 'Seafood',
                'aliases' => ['udang', 'cumi', 'lobster', 'kepiting', 'grilled fish', 'salmon', 'tuna steak', 'prawn'],
                'visual_keywords' => [
                    'vibrant fresh seafood color', 'perfect grill marks', 'glistening butter glaze',
                    'lemon wedge accent', 'fresh herbs scattered',
                ],
                'texture_descriptors' => ['firm yet tender flesh', 'caramelized exterior', 'moist and flaky interior'],
                'lighting_preset' => 'bright clean light, fresh oceanic feel',
                'camera_angle' => 'overhead or 45 degree showing full dish',
                'plating_style' => 'white plate or dark slate, lemon half, fresh dill or parsley, melted butter in small ramekin',
                'color_palette' => ['coral orange prawn', 'deep red lobster', 'bright lemon yellow', 'herb green'],
                'avoid' => ['overcooked grey seafood', 'dry texture look', 'frozen appearance'],
                'cuisine_affinity' => ['fine_dining', 'western', 'indonesian'],
                'sort_order' => 11,
            ],
            [
                'key' => 'croissant',
                'name' => 'Croissant & Pastry',
                'aliases' => ['pastry', 'danish', 'pain au chocolat', 'croissant butter', 'kouign amann', 'roti croissant'],
                'visual_keywords' => [
                    'perfect golden laminated layers', 'honeycomb interior crumb visible at cut',
                    'slight glaze sheen', 'flaky exterior texture', 'butter pools in crevices',
                ],
                'texture_descriptors' => ['shatteringly crisp exterior', 'airy honeycomb interior', 'buttery rich layers'],
                'lighting_preset' => 'soft morning natural light, warm golden hour feel, bright and fresh',
                'camera_angle' => 'overhead flat lay OR 3/4 showing cross section',
                'plating_style' => 'white marble surface, parchment paper, small butter curl, coffee cup in background blur',
                'color_palette' => ['deep golden amber', 'cream butter white', 'warm brown glaze', 'marble grey surface'],
                'avoid' => ['pale underbaked color', 'collapsed layers', 'uneven bake'],
                'cuisine_affinity' => ['western_cafe', 'french'],
                'sort_order' => 12,
            ],
            [
                'key' => 'smoothie_bowl',
                'name' => 'Smoothie Bowl & Healthy',
                'aliases' => ['acai bowl', 'granola bowl', 'smoothie bowl', 'overnight oats', 'yogurt bowl', 'pitaya bowl'],
                'visual_keywords' => [
                    'vibrant color base', 'artful topping rows', 'granola clusters',
                    'fresh fruit slices', 'drizzle of honey or nut butter',
                ],
                'texture_descriptors' => ['thick creamy base', 'crunchy granola contrast', 'fresh juicy fruit'],
                'lighting_preset' => 'bright clean natural daylight, fresh and vibrant',
                'camera_angle' => 'pure overhead flat lay',
                'plating_style' => 'wide shallow ceramic bowl, toppings in rows, edible flowers optional, clean white or wooden surface',
                'color_palette' => ['deep purple acai', 'bright tropical fruits', 'golden granola', 'green kiwi accent'],
                'avoid' => ['melted runny base', 'random messy toppings', 'dull muted colors'],
                'cuisine_affinity' => ['western_cafe', 'healthy'],
                'sort_order' => 13,
            ],
            [
                'key' => 'cocktail',
                'name' => 'Minuman & Drinks',
                'aliases' => ['mocktail', 'signature drink', 'fruit punch', 'sparkling drink', 'milkshake', 'fruit tea', 'es kopi', 'minuman segar', 'juice'],
                'visual_keywords' => [
                    'vibrant liquid color', 'perfect ice cubes', 'condensation droplets on glass',
                    'garnish perched on rim', 'liquid layers',
                ],
                'texture_descriptors' => ['crystal clear ice', 'frothy top', 'layered color gradient'],
                'lighting_preset' => 'backlit for translucency, bright and refreshing',
                'camera_angle' => 'eye level showing full glass height',
                'plating_style' => 'tall clear glass, colorful straw, fruit slice on rim, mint sprig, marble or dark bar counter surface',
                'color_palette' => ['vibrant fruit colors', 'clear ice', 'bright garnish', 'dark moody bar background'],
                'avoid' => ['flat no-carbonation look', 'melted ice', 'plain boring glass'],
                'cuisine_affinity' => ['western_cafe', 'indonesian'],
                'sort_order' => 14,
            ],
        ];

        foreach ($categories as $cat) {
            FoodCategory::updateOrCreate(['key' => $cat['key']], $cat);
        }
    }
}